// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordNET_Server_2._0.DBRelations;

#nullable disable

namespace WordNET_Server_2._0.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordNET_Server_2._0.Models.AssociatedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatisticsId")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("AssociatedWord");
                });

            modelBuilder.Entity("WordNET_Server_2._0.Models.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociatedWordId")
                        .HasColumnType("int");

                    b.Property<int>("ManAvarageAge")
                        .HasColumnType("int");

                    b.Property<int>("ManCount")
                        .HasColumnType("int");

                    b.Property<int>("WomanAvarageAge")
                        .HasColumnType("int");

                    b.Property<int>("WomanCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedWordId")
                        .IsUnique();

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("WordNET_Server_2._0.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("WordNET_Server_2._0.Models.AssociatedWord", b =>
                {
                    b.HasOne("WordNET_Server_2._0.Models.Word", null)
                        .WithMany("AssociatedWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordNET_Server_2._0.Models.Statistics", b =>
                {
                    b.HasOne("WordNET_Server_2._0.Models.AssociatedWord", null)
                        .WithOne()
                        .HasForeignKey("WordNET_Server_2._0.Models.Statistics", "AssociatedWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordNET_Server_2._0.Models.Word", b =>
                {
                    b.Navigation("AssociatedWords");
                });
#pragma warning restore 612, 618
        }
    }
}
